image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  GITLAB_REGISTRY: registry.gitlab.com
  DOCKERHUB_REGISTRY: docker.io
  IMAGE_NAME: $DOCKER_REGISTRY/nicosingh/rabbitmq-cluster-swarm

services:
  - docker:dind

stages:
  - build-branch
  - build-master

branch-gitlab:
  stage: build-branch
  except:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $GITLAB_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME

branch-docker_hub:
  stage: build-branch
  except:
    - master
  script:
    - docker login -u nicosingh -p $DOCKERHUB_NICOSINGH_PASSWORD $DOCKERHUB_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME

master-gitlab:
  stage: build-master
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $GITLAB_REGISTRY
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

master-docker_hub:
  stage: build-master
  only:
    - master
  script:
    - docker login -u nicosingh -p $DOCKERHUB_NICOSINGH_PASSWORD $DOCKERHUB_REGISTRY
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
