image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  DOCKER_REGISTRY: registry.gitlab.com
  IMAGE_NAME: $DOCKER_REGISTRY/nicosingh/rabbitmq-cluster-swarm

services:
  - docker:dind

stages:
  - build-docker

build-branch:
  stage: build-docker
  except:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME

build-master:
  stage: build-docker
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
