image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  DOCKER_REGISTRY: registry.gitlab.com
  IMAGE_NAME_TEST: $DOCKER_REGISTRY/nicosingh/rabbitmq-cluster-swarm:$CI_COMMIT_REF_NAME
  IMAGE_NAME_RELEASE: $DOCKER_REGISTRY/nicosingh/rabbitmq-cluster-swarm:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - deploy

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY
    - docker build -t $IMAGE_NAME_TEST .
    - docker push $IMAGE_NAME_TEST

push:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY
    - docker build -t $IMAGE_NAME_RELEASE .
    - docker push $IMAGE_NAME_RELEASE
