image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - deploy

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/nicosingh/rabbitmq-cluster-swarm .

push:
  stage: deploy
  script:
    - docker push registry.gitlab.com/nicosingh/rabbitmq-cluster-swarm
