version: "3"
services:
  rabbit-master:
    image: registry.gitlab.com/nicosingh/rabbitmq-cluster-swarm:latest
    ports:
      - "5673:5672"
      - "15673:15672"
    hostname: rabbit-master
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - RABBITMQ_ERLANG_COOKIE=dockerClusterCookie
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=rabbitpass
      - RABBITMQ_DEFAULT_VHOST=/
      - TZ="America/Santiago"

  rabbit-slave:
    image: registry.gitlab.com/nicosingh/rabbitmq-cluster-swarm:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: global
      placement:
        constraints: [node.role != manager]
    environment:
      - SLAVE=true
      - RABBITMQ_ERLANG_COOKIE=dockerClusterCookie
      - TZ="America/Santiago"

  rabbit-exporter:
    image: kbudde/rabbitmq-exporter
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - "RABBIT_URL=http://rabbit-master:15672"
      - RABBIT_USER=rabbituser
      - RABBIT_PASSWORD=rabbitpass
      - TZ="America/Santiago"

  prometheus:
    image: registry.gitlab.com/nicosingh/prometheus:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
    environment:
      - TZ="America/Santiago"
