version "3"

services:

  rabbit-master:
    image: nicosingh/rabbitmq-cluster-swarm:latest
    ports:
      - "15672:15672"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - RABBITMQ_ERLANG_COOKIE=dockerClusterCookie
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=rabbitpass
      - RABBITMQ_DEFAULT_VHOST=development

  rabbit-slave:
    image: nicosingh/rabbitmq-cluster-swarm:latest
    deploy:
      mode: global
      placement:
        constraints: [node.role != manager]
    environment:
      - SLAVE=true
      - RABBITMQ_ERLANG_COOKIE=dockerClusterCookie
