version: "3"
services:
  rabbit-master:
    image: nicosingh/rabbitmq-cluster-swarm:latest
    ports:
      - "5673:5672"
      - "15673:15672"
    hostname: rabbit-master
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - RABBITMQ_ERLANG_COOKIE=dockerClusterCookie
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=rabbitpass
  rabbit-slave:
    image: nicosingh/rabbitmq-cluster-swarm:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: global
      placement:
        constraints: [node.role != manager]
    environment:
      - SLAVE=true
      - RABBITMQ_ERLANG_COOKIE=dockerClusterCookie
